"""Snake language transpiler — converts AST to executable Python source."""

import ast as python_ast
from snake.parser import (
    PrintNode, AssignNode, IfNode, LoopNode, FuncDefNode, CallNode,
    BinOpNode, NumberNode, StringNode, IdentifierNode, InputNode,
)


class Transpiler:
    """Converts Snake AST into valid Python source code."""

    def __init__(self):
        self.indent_level: int = 0

    def transpile(self, nodes: list) -> str:
        """Convert a list of AST nodes into a Python source string.

        Args:
            nodes: Top-level AST nodes from the parser.

        Returns:
            A syntactically valid Python source code string.
        """
        lines = ["# Generated by Snake Transpiler", ""]
        for node in nodes:
            lines.append(self.gen(node))
        output = "\n".join(lines) + "\n"
        # Validate output
        python_ast.parse(output)
        return output

    def indent(self) -> str:
        """Return the current indentation string."""
        return "    " * self.indent_level

    def gen(self, node) -> str:
        """Dispatch to the appropriate gen_* method."""
        method_name = f"gen_{type(node).__name__}"
        method = getattr(self, method_name, None)
        if method is None:
            return f"{self.indent()}# Unsupported: {type(node).__name__}"
        return method(node)

    def gen_PrintNode(self, node: PrintNode) -> str:
        """Generate: print(...)"""
        args = ", ".join(self.gen_expr(v) for v in node.values)
        return f"{self.indent()}print({args})"

    def gen_AssignNode(self, node: AssignNode) -> str:
        """Generate: name = value"""
        return f"{self.indent()}{node.name} = {self.gen_expr(node.value)}"

    def gen_IfNode(self, node: IfNode) -> str:
        """Generate: if condition: / else:"""
        lines = [f"{self.indent()}if {self.gen_expr(node.condition)}:"]
        self.indent_level += 1
        for stmt in node.then_body:
            lines.append(self.gen(stmt))
        self.indent_level -= 1

        if node.else_body:
            lines.append(f"{self.indent()}else:")
            self.indent_level += 1
            for stmt in node.else_body:
                lines.append(self.gen(stmt))
            self.indent_level -= 1

        return "\n".join(lines)

    def gen_LoopNode(self, node: LoopNode) -> str:
        """Generate: for _ in range(N):"""
        lines = [f"{self.indent()}for _ in range({self.gen_expr(node.count)}):"]
        self.indent_level += 1
        for stmt in node.body:
            lines.append(self.gen(stmt))
        self.indent_level -= 1
        return "\n".join(lines)

    def gen_FuncDefNode(self, node: FuncDefNode) -> str:
        """Generate: def name():"""
        lines = [f"{self.indent()}def {node.name}():"]
        self.indent_level += 1
        for stmt in node.body:
            lines.append(self.gen(stmt))
        self.indent_level -= 1
        return "\n".join(lines)

    def gen_CallNode(self, node: CallNode) -> str:
        """Generate: name()"""
        return f"{self.indent()}{node.name}()"

    def gen_expr(self, node) -> str:
        """Generate a Python expression string from an expression node."""
        if isinstance(node, NumberNode):
            return repr(node.value)

        if isinstance(node, StringNode):
            return repr(node.value)

        if isinstance(node, IdentifierNode):
            return node.name

        if isinstance(node, InputNode):
            return f"input({repr(node.prompt)})"

        if isinstance(node, BinOpNode):
            left = self.gen_expr(node.left)
            right = self.gen_expr(node.right)
            return f"({left} {node.op} {right})"

        return "None"
